
# excel开始解析行数
EXCEL_PARSE_DIALOG_START_ROW = 1
EXCEL_PARSE_CHARACTER_START_ROW = 1
EXCEL_PARSE_IMAGE_START_ROW = 1

# excel解析列数
EXCEL_PARSE_DIALOG_START_COL = 18
EXCEL_PARSE_CHARACTER_START_COL = 5
EXCEL_PARSE_IMAGE_START_COL = 2
